### ISSUE TITLE
Docs: Guidance on disabling ASP.Net Core console logging

### ISSUE THREAD

**Issue by BennieCopeland** [nspec/DotNetTestNSpec#6]
Running functional tests against an ASP.Net Core web application project clutters the test output window with logging information. This is caused by the line ```loggerFactory.AddConsole(this.Configuration.GetSection("Logging"));``` in the ```Configure``` method of the ```Startup``` class. I've commented out this line for now until a better solution is found.

**Comment by BrainCrumbz** [comment]
Just to have a common understanding: while running tests with `dotnet test`, you see output from tests (like `dotnet-test-nspec version: 0.1.0.0`) intermixed with output from application logging code?

Not sure if there's a "standard" way to act on this in ASP.NET Core examples. But in general: if during tests you want to disable application logging, it makes sense to consider a specific build configuration for tests. 

So e.g. besides *Development* and *Release*, have a *Test* build configuration. Next to that, create a `appsettings.Test.json`, where you can override `Logging` section copied from `appsettings.json`:

```json
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information",  // ### Change this one
      "System": "Warning",
      "Microsoft": "Warning"
    }
  }
```

**Comment by BennieCopeland** [comment]
Correct. The following is an example:

```
dotnet-test-nspec version: 0.1.0.0
NSpec version: 2.0.0.0
Organization Feature
  When creating an Organization
    that does not exist
      I am notified that it has been created (4s)
        //Console output
        info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
              Request starting HTTP/1.1 GET http://
        info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
              Executing action method TSC.Services.Authentication.Api.Features.Organization.OrganizationsController.Post
Async (TSC.Services.Authentication.Api) with arguments (TSC.Services.Authentication.Api.Features.Organization.Post+Reque
stModel, System.Threading.CancellationToken) - ModelState is Valid
        info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
              Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
        info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
              Executed action TSC.Services.Authentication.Api.Features.Organization.OrganizationsController.PostAsync (T
SC.Services.Authentication.Api) in 626.9299ms
        info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
              Request finished in 998.1021ms 201
      The information is stored in the database (2s)
        //Console output
        info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
              Request starting HTTP/1.1 GET http://
        info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
              Executing action method TSC.Services.Authentication.Api.Features.Organization.OrganizationsController.Post
Async (TSC.Services.Authentication.Api) with arguments (TSC.Services.Authentication.Api.Features.Organization.Post+Reque
stModel, System.Threading.CancellationToken) - ModelState is Valid
        info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
              Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
        info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
              Executed action TSC.Services.Authentication.Api.Features.Organization.OrganizationsController.PostAsync (T
SC.Services.Authentication.Api) in 24.3473ms
        info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
              Request finished in 32.3409ms 201
2 Examples, 0 Failed, 0 Pending
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.
```

There was no need to create a specific build configuration for testing. I already had an ```appsettings.json``` file in my test project for the test database connection string. Following what you suggested, I changed the ```Logging``` setting in my test projects ```appsettings.json```. I needed to change Default, System, and Microsoft to ```Warning``` as they were all set to ```Information```. I just needed to ensure that the test projects ```appsettings.json``` file is copied to the output directory by changing the ```buildOptions``` of the test projects ```project.json``` file.
```
"buildOptions": {
    "debugType": "portable",
    "copyToOutput": {
      "include": [ "appsettings.json" ]
    }
  }
```

**Comment by BrainCrumbz** [comment]
Closing this, there seems to be nothing more needed. Please feel free to reopen.
