### ISSUE TITLE
Docs: Guidance on using the NSpec test runner

### ISSUE THREAD

**Issue by BennieCopeland** [nspec/DotNetTestNSpec#7]
For those wondering how to get started, this is what I figured out so far.

1. Create a new xunittest project by running the command ```dotnet new -t xunittest```
2. Replace ```xunit``` nuget package in the ```project.json``` with ```"NSpec": "2.0.0"```
3. Replace ```dotnet-test-xunit``` nuget package in the ```project.json``` with ```"dotnet-test-nspec": "0.1.0"```
4. Replace ```xunit``` in the ```testRunner``` setting of the ```project.json``` file with ```nspec```
5. Run ```dotnet restore``` followed by ```dotnet test``` to restore and execute the test project.

**Comment by BrainCrumbz** [comment]
If you don't mind I'm going to close this and redirect it to the same issue in NSpec project (https://github.com/nspec/NSpec/issues/164).

Also, if it might be useful, have a look at a ready-made sample: [DotNetTestSample](https://github.com/nspec/DotNetTestNSpec/blob/master/sln/test/Samples/DotNetTestSample)

**Comment by BennieCopeland** [comment]
Sample link doesn't work.

**Comment by BrainCrumbz** [comment]
Doh! Gonna fix it right away on readme as well:

https://github.com/nspec/NSpec/tree/master/sln/test/Samples/DotNetTestSample
